version: '3.8'

services:
    frontend_prod:
            container_name: frontend_prod
            build:
                context: ./frontend
                dockerfile: Dockerfile
                # target: production
            command: npm start
            restart: always
            ports:
            - "4200:4200"
            depends_on: 
                  - db
    #Prod for Nest.js.
    backend_prod:
        container_name: api_prod
        build:
            context: ./backend
            target: production
            dockerfile: Dockerfile
        command: npm run start:prod
        ports:
            - 3000:3000
        restart: always
    #MySQL databse
    db:
        container_name: db
        image: mysql
        restart: always
        volumes:
        - mysqldb:/var/lib/mysql
    #Redis db cacheing
    db_cache:
        container_name: db_cache
        image: redis:6.2-alpine
        restart: always
        depends_on:
            - db
        command: redis-server
volumes:
    mysqldb: